#!/usr/bin/perl -w
use POSIX qw(strftime);


#sudo apt-get install  libsoap-lite-perl
#sudo apt-get install libdbd-mysql-perl
#sudo apt-get install libdbi-perl
#sudo apt-get install  libxml-simple-perl
#sudo apt-get install libdbd-pg-perl


use SOAP::Lite (+trace =>"all", readable => 1);
#( +trace => , maptype => {} );;
use DBI;
use MIME::Base64;
use XML::Simple;
 
$db = DBI->connect("DBI:Pg:host=localhost;dbname=weather","weather","31415") or die "No access to database: $!";

#$insert
$insert = "INSERT INTO stations (id,  idd, code, namestation, updateperiod, useraccessright, login, password_soap, address, place, latitude, longitude, date_time_in, date_time_out, is_present)  VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; #stations list

$query_ins = $db->prepare("$insert");
$start = 0;

$select = "SELECT * FROM stations ORDER BY id DESC";
$query_id = $db->prepare("$select");
	$query_id->execute();

	if ($query_id->rows >0){
	@row = $query_id->fetchrow_array;
	$start = $row[11];
	}

# connection parameters section. It's need only in first time.
$ip = 'http://127.0.0.1:8080'; #ReplicationApiService';


$method_getstations = "GetStations";

$password = '31415';
$user = 'weather';

# end connection parameters section


$client=SOAP::Lite->proxy( $ip);
$client->uri("urn:ReplicationApiService");

$client->readable(1);
$client->on_action( sub {  join '', '"'.$ip,qq($_[1]")} );


$obj_login = SOAP::Data->new(name => 'login', value => $user);
$obj_pwd = SOAP::Data->new(name => 'password', value => $password);

 #print 'arg is - '.@arg['login'];
 $Username = SOAP::Header->name('login' => $user);
 $Password = SOAP::Header->name('password' => $password);
         
 $UsernameToken = SOAP::Header->value($Username, $Password);
 $security = SOAP::Header->name('AuthHeaderInfo')->attr({'xmlns' => $ip})->value(\$UsernameToken);


# make the call
#$som = $client->GetStations(  $security);
#print ($result . "\n\n");

$som = $client->call($method_getstations, $obj_login, $obj_pwd ,$security );
die $som->faultstring if ($som->fault);

#$elm = SOAP::Deserializer->deserialize(XMLout($som->body));

$i=0;

for  $t ($som->valueof('//GetStationsResponse/GetStationsResult/StationsInfo')) {
      print $t->{ID} . " - " . $t->{Code} . " - " . $t->{Name} . " - " . $t->{UpdatePeriod} ." - " . $t->{UserAccessRight} ."\n";
	$select = "SELECT * FROM stations WHERE idd = '" . $t->{ID} . "'";
	#print ("Select is " .  localtime() . "\n");
	$query = $db->prepare("$select");
	$query->execute();

		if ($query->rows <1)
	{	

		$query_ins->execute($start+1, $t->{ID}, $t->{Code}, $t->{Name}, $t->{UpdatePeriod}, $t->{UserAccessRight}, $user, $password, $ip,
		$t->{Place}, $t->{Latitude}, $t->{Longitude}, strftime ("%F %X", localtime()),strftime ("%F %X", localtime()), 1);
		$i++;

	};

    }
$query->finish;
$query_ins ->finish;
$query_id -> finish;
#

print ("\nthere are " . $i . " records added\n");
$db->disconnect;
#print "Result is: ". XMLout($elm)."\n\n";
#print "Result is: ". $som->dataof('//GetStationsResponse/GetStationsResult/StationInfo/*'). "...\n\n";

